language: node_js
node_js:
- '4.0'
- '8.0'
deploy:
  provider: releases
  api_key:
    secure: rDw8ONsycSRx2L28k5RWnr6T5TO1sUg3iqTXq6HnPrdbA6cAhlbWqvqdeBOINjr3HDEOnB7/LikmyZIEiKh4Be+Ptl1qytz+0ZVjWO0IFX+omhO6jsfVbcVybP4KFDiBeotA1OzvhOiIvVbYb2wNBs8w6cNODg2u+G3gTRzUa/MZIdb1F4ZtRGUWcGMqBpiPBIIfagjOcR/9VRQbrCb1CQlziD8iI7iAonQIQgScVlun56gGAN2JvnoPwEYb2EgJV+1jD7p3gwpdtC7/ovKMSxazQnGhAWKYWyzmOTCNlblPh+SPbWgZucspHR39MLnBEu8poV/BryB3mSSONqShra5VNQIJSu6v8TmoioZNCXbHsqznAaVpdbsxG9JwiR+74GQd5MjNEbcQDXlLzKQ3aUD8FfUEMvVVzPqm1LDhY9O0FXH/job4689Ei+ywW2QxEg5GvLEP3EcZYPawyqmmSz2lbU2iS5ngMpVbVLTJJF3inWwNczXD59Gxnt2/J25sFurWaKDqWV8mAqde7pRFAXBRDhhj2HPWwxYwbcgaspyU4L35RE1ZcNVqGtYIqr86jHaRnzkqtsD7cANxjV1eWyTf9nJDErq6yPsA5Aw1Y2LDUwZXYfZ01WMgUSbX55NafGGOq60QLwI9hJSH+OuV5/8d9enIrDfqIm22/OeNbzM=
  file:
    - "iso-15924.js"
    - "iso-15924.min.js"
  on:
    tags: true
    node: '8.0'
