language: node_js
node_js:
- '4.0'
- '8.0'
deploy:
  - provider: npm
    email: tituswormer@gmail.com
    api_key:
      secure: LOxUCYH2vmliKyRYmmy/aepaGrct8ZKDLeMqsed1+6PE+zYd63qGt3uOKrHHr4+J2f+scRQqpovpLDkCi/2uIV0GHh/ui6y2olEVjQENiu+dYA3g0n9fK7ovlFeUgI1cunhj91AqEtB3lHSM4tf7U5qcUNGe0rdVrziuQ+k26X8PxUxl22thSw4lpR3iW0d/PoXXws7OvIy7Y9i9eGCXZLkRf+hSZ+oNuqpttRAcXAazIZqUbXoF8jjno1YHcj5x9PXulsdPvM7uQqAEM/NRBxQKxZp/6RuS7c3MlgGakPfc8Ybnz75Wjac/G/vBCBba9gtbTdMr3PpaD8jjAZmJm4X1iQ1MfknSCVao60pLrp3QFk9PvoEHoU6OkxITN94aNHKhwlsZYK72mMx2Dd7FMMXI6BYoOByXwFgVvVQEU4JT8BIyWWm71BMDhGEa+EFlYt04ykQMlnGusanKJ3dlx2NsEWYAGY7OTUjMgF5d78J7RYJVKl/jGNxnuUu/++SVYeuTuJlGXOJPwaGo/GM5MnWPd3ZS+Xe9FDFXjKJKelSXIk8refN6bh9iXZri8Tkc+vhdSEnYyEzgpXv+lRrY1+jpnAcXf5uXdRIUqqtFOuOj9NAi/5v8Fw+TCmKKAveuqqM3Zer0x3WUXjHI55XOl/gKI/0Ss0buDx+IX1BLo58=
    on:
      tags: true
      node: '4.0'
  - provider: releases
    api_key:
      secure: rDw8ONsycSRx2L28k5RWnr6T5TO1sUg3iqTXq6HnPrdbA6cAhlbWqvqdeBOINjr3HDEOnB7/LikmyZIEiKh4Be+Ptl1qytz+0ZVjWO0IFX+omhO6jsfVbcVybP4KFDiBeotA1OzvhOiIvVbYb2wNBs8w6cNODg2u+G3gTRzUa/MZIdb1F4ZtRGUWcGMqBpiPBIIfagjOcR/9VRQbrCb1CQlziD8iI7iAonQIQgScVlun56gGAN2JvnoPwEYb2EgJV+1jD7p3gwpdtC7/ovKMSxazQnGhAWKYWyzmOTCNlblPh+SPbWgZucspHR39MLnBEu8poV/BryB3mSSONqShra5VNQIJSu6v8TmoioZNCXbHsqznAaVpdbsxG9JwiR+74GQd5MjNEbcQDXlLzKQ3aUD8FfUEMvVVzPqm1LDhY9O0FXH/job4689Ei+ywW2QxEg5GvLEP3EcZYPawyqmmSz2lbU2iS5ngMpVbVLTJJF3inWwNczXD59Gxnt2/J25sFurWaKDqWV8mAqde7pRFAXBRDhhj2HPWwxYwbcgaspyU4L35RE1ZcNVqGtYIqr86jHaRnzkqtsD7cANxjV1eWyTf9nJDErq6yPsA5Aw1Y2LDUwZXYfZ01WMgUSbX55NafGGOq60QLwI9hJSH+OuV5/8d9enIrDfqIm22/OeNbzM=
    file:
      - "iso-15924.js"
      - "iso-15924.min.js"
    on:
      tags: true
      node: '8.0'
